Changes: - use updated version

diff --git a/trunk/release_functions b/trunk/release_functions
--- a/trunk/release_functions
+++ b/trunk/release_functions
@@ -1,9 +1,10 @@
 # ===================================================================
 # Release script for libgds/cbgp: release functions
-# Last modified: 17/11/2006 (bqu)
+# Last modified: 25/10/2007 (bqu)
 # ===================================================================
 
 declare -a CONF_OPTIONS
+declare -a VALID_EXECS
 declare -r LINE="--------------------------------\
 	-------------------------------------"
 
@@ -140,7 +141,7 @@ check_project_version()
     if [ ! -z "$LIBRARY_VERSION" ]; then
 	info "Checking project/library versions..."
 	echo "  library: $LIBRARY_VERSION"
-	local PROJECT_VERSION_SHORT=`echo "$PROJECT_VERSION" | sed 's:^\([0-9]*\.[0-9]*\.[0-9]*\).*$:\1:'`
+	local PROJECT_VERSION_SHORT=`echo "$PROJECT_VERSION" | sed 's:^\([0-9]*\.[0-9]*\).*$:\1:'`
 	echo "  project: $PROJECT_VERSION_SHORT"
 	if [ "$PROJECT_VERSION_SHORT" != "$LIBRARY_VERSION" ]; then
 	    error "project/library versions mismatch."
@@ -159,19 +160,40 @@ check_project_version()
 check_build()
 {
     local OPTIONS
+    local SAVE_PWD
+    local i
+
     info "Checking build..."
-    if [ ! -z "$PREBUILD" ]; then
-	eval "$PREBUILD $REDIRECT"
-	if [ $? != 0 ]; then
-	    error "prebuild command failed."
-	fi
+    if [ $BUILD -ne 1 ]; then
+	echo "    skipped"
+	return 0
     fi
-    for (( i= ${#CONF_OPTIONS[*]}-1 ; $i >= 0 ; i-- )) do
+
+    SAVE_PWD=$PWD
+    cd $BUILDROOT
+
+    PACKAGE_NAME="$MODULE-$VERSION"
+    PACKAGE_FILE="$PACKAGE_NAME.tar.gz"
+    eval "tar xvzf $SAVE_PWD/$PACKAGE_FILE $REDIRECT"
+    if [ $? != 0 ]; then
+	error "could not extract package from archive."
+    fi
+    
+    eval "cd $PACKAGE_NAME $REDIRECT"
+    if [ $? != 0 ]; then
+	error "could not enter package directory."
+    fi
+
+    for (( i= 0 ; i < ${#CONF_OPTIONS[*]} ; i++ )) do
 	OPTIONS="${CONF_OPTIONS[$i]}"
+	let i_display=i+1
+	info "Checking build option ($i_display/${#CONF_OPTIONS[*]}):"
 	check_configure "$OPTIONS"
 	check_compilation
 	check_validation
     done
+
+    cd $SAVE_PWD
 }
 
 # -----[ check_configure ]-------------------------------------------
@@ -179,13 +201,11 @@ check_configure()
 {
     local CONF_OPTIONS=$1
     info "+ Checking configure $CONF_OPTIONS..."
-    if [ $BUILD -eq 1 ]; then
-	eval "./configure $CONF_OPTIONS_COMMON $CONF_OPTIONS $REDIRECT"
-	if [ $? != 0 ]; then
-	    error "failed to configure."
-	fi
-    else
-	echo "    skipped"
+
+    eval "./configure --prefix=$BUILDROOT/local \
+        $CONF_OPTIONS_COMMON $CONF_OPTIONS $REDIRECT"
+    if [ $? != 0 ]; then
+	error "failed to configure."
     fi
 }
 
@@ -193,23 +213,30 @@ check_configure()
 check_compilation()
 {
     info "+ Checking compilation..."
-    if [ $BUILD -eq 1 ]; then
-	eval "make clean $REDIRECT"
-	if [ $? != 0 ]; then
-	    error "compilation failed (make clean)."
-	fi
-	eval "make $REDIRECT"
-	if [ $? != 0 ]; then
-	    error "compilation failed (make)."
-	fi
-    else
-	echo "    skipped"
+
+    eval "make clean $REDIRECT"
+    if [ $? != 0 ]; then
+	error "compilation failed (make clean)."
+    fi
+    eval "make $REDIRECT"
+    if [ $? != 0 ]; then
+        error "compilation failed (make)."
     fi
 }
 
 # -----[ make_dist ]-------------------------------------------------
 make_dist() {
     info "Building distribution..."
+
+    if [ ! -z "$PREBUILD" ]; then
+	eval "$PREBUILD $REDIRECT"
+	if [ $? != 0 ]; then
+	    error "prebuild command failed."
+	fi
+    fi
+
+    check_configure
+
     eval "make dist $REDIRECT"
     if [ $? != 0 ]; then
 	error "unable to build distribution (make dist)."
@@ -226,12 +253,19 @@ make_dist() {
 # -----[ check_validation ]------------------------------------------
 check_validation()
 {
-    if [ ! -z "$VALID_EXEC" ]; then
-	info "+ Checking validation..."
-	eval "$VALID_EXEC $REDIRECT"
-	if [ $? != 0 ]; then
-	    error "validation failed."
-	fi
+    local VALID_EXEC
+    local i
+
+    if [ ! -z "$VALID_EXECS" ]; then
+	for (( i= 0 ; i < ${#VALID_EXECS[*]} ; i++ )) do
+	    VALID_EXEC="${VALID_EXECS[$i]}"
+	    let i_display=i+1
+	    info "+ Checking validation ($i_display/${#VALID_EXECS[*]})..."
+	    eval "$VALID_EXEC $REDIRECT"
+	    if [ $? != 0 ]; then
+	        error "validation failed."
+	    fi
+	done
     fi
 }
 
@@ -379,6 +413,9 @@ src_release_check_parameters()
     else
 	RELEASE_MODE=0 # Minor
     fi
+    if [ -z $BUILDROOT ]; then
+        error "BUILDROOT variable not defined"
+    fi
 }
 
 # -----[ src_release_parse_arguments ]-------------------------------
@@ -451,7 +488,14 @@ make_release()
 	check_svn_status
     fi
     check_project_version
-    check_build;
+
+    # ===================================================================
+    # Part II. Build/test distribution package (.tar.gz)
+    # ===================================================================
+    info_part "II. Building/testing distribution package"
+    make_dist
+
+    check_build
     if [ $TEST_ONLY -eq 1 ]; then
 	read_yes_no "Build release ?" "N"
 	if [ "$READ_YES_NO_RESULT" = "y" ]; then
@@ -463,11 +507,10 @@ make_release()
 	fi
     fi
 
-
     # ===================================================================
-    # Part II. Building release
+    # Part III. Building release
     # ===================================================================
-    info_part "II. Building release"
+    info_part "III. Building release"
     if [ $RELEASE -eq 1 ]; then
 	info "Building the release"
 	if [ $RELEASE_MODE -eq 0 ]; then
@@ -503,11 +546,10 @@ make_release()
 	    fi
 	fi
     fi
-    make_dist
 
 
     # ===================================================================
-    # Part III. Publish distribution
+    # Part IV. Publish distribution
     # ===================================================================
     if [ ! $PUBLISH -eq 1 ]; then
 	read_yes_no "Publish package ?" "Y"
@@ -516,7 +558,7 @@ make_release()
 	fi
     fi
     if [ $PUBLISH -eq 1 ]; then
-	info_part "III. Publishing release"
+	info_part "IV. Publishing release"
 	echo "Publishing distribution"
 	for f in $PUBLISH_FILES; do
 	    scp -C $f $PUBLISH_URL
@@ -527,12 +569,13 @@ make_release()
     fi
 
     # ===============================================================
-    # Part IV. Display last recommendations
+    # Part V. Display last recommendations
     # ===============================================================
-    echo "***** Last recommendations *****"
+    echo "***** Last recommendations ********************************"
     echo "Do not forget"
     echo "- to build the packages (.rpm, .deb, ...)"
     echo "- to send an e-mail to the mailing-list"
     echo "- do not forget to announce the new release on the web site"
-    echo "********************************"
+    echo "- to list the changes provided in this release"
+    echo "***********************************************************"
 }
